const token=localStorage.getItem('jz-account-token');
if(!token)location.href=`auth.html?next=${encodeURIComponent(location.pathname+location.hash)}`;
const esc=value=>{const element=document.createElement('span');element.textContent=String(value??'');return element.innerHTML};
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(value)||0);
const date=value=>value?new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—';
let data=null,activeView='overview';
async function api(url,options={}){const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}}),result=await response.json().catch(()=>({}));if(response.status===401){localStorage.removeItem('jz-account-token');location.href='auth.html';throw new Error('Session expired')}if(!response.ok)throw new Error(result.error||'Request failed');return result}
function toast(message){const item=document.querySelector('#accountToast');item.textContent=message;item.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>item.classList.remove('show'),2200)}
const empty=message=>`<div class="empty-account">${esc(message)}</div>`;
const courseProgress=id=>data.customer.progress?.[id]?.percent||0;
function setView(view){activeView=view;document.querySelectorAll('[data-account-view]').forEach(button=>button.classList.toggle('active',button.dataset.accountView===view));document.querySelectorAll('.account-view').forEach(panel=>panel.classList.toggle('active',panel.id===`${view}View`));const titles={overview:['Your JZ world','Overview'],academy:['Learning dashboard','My Academy'],orders:['Purchases and delivery','My orders'],saved:['Your shortlist','Saved items'],reviews:['Your voice','Reviews'],support:['Direct help','Support'],profile:['Account settings','Profile']};document.querySelector('#accountEyebrow').textContent=titles[view][0];document.querySelector('#accountViewTitle').textContent=titles[view][1];history.replaceState(null,'',`#${view}`);closePanels()}
function renderCourseCard(entry){const course=entry.course||entry,progress=courseProgress(course.id);return `<article class="account-course"><div class="account-course-visual" ${course.coverImage?`style="background-image:linear-gradient(rgba(10,14,10,.25),rgba(10,14,10,.72)),url('${esc(course.coverImage)}');background-size:cover;background-position:center"`:''}><small>${esc(course.game||'JZ Academy')} / ${esc(course.level||'All levels')}</small><strong>${esc(course.title)}</strong></div><div class="account-course-copy"><span>${progress}% complete</span><h3>${esc(course.title)}</h3><p>${esc(course.description||'Continue building your practical skills.')}</p><div class="mini-progress"><i style="width:${progress}%"></i></div><a href="learn.html?id=${encodeURIComponent(course.id)}"><span>${progress?'Continue':'Start course'}</span><b>→</b></a></div></article>`}
function renderOrder(order){return `<article class="account-order"><header><div><strong>${esc(order.number)}</strong><small>${date(order.createdAt)} · ${esc(order.deliveryName||'Delivery')}</small></div><div><strong>${money(order.total)}</strong><small>${esc(order.paymentStatus)} · ${esc(order.paymentMethod)}</small></div><span class="order-status">${esc(order.status)}</span></header><div class="account-order-items">${order.items.map(item=>`${item.quantity} × ${esc(item.name)}${item.variant?` · ${esc(item.variant)}`:''}`).join('<br>')}${order.trackingNumber?`<br><strong>Tracking: ${esc(order.trackingNumber)}</strong>`:''}</div></article>`}
function render(){
  const customer=data.customer,completed=data.courses.filter(entry=>courseProgress(entry.courseId)===100);
  document.querySelector('#accountFirstName').textContent=customer.name.split(/\s+/)[0];document.querySelector('#metricCourses').textContent=data.courses.length;document.querySelector('#metricCompleted').textContent=completed.length;document.querySelector('#metricOrders').textContent=data.orders.length;document.querySelector('#metricSaved').textContent=data.savedProducts.length+data.savedCourses.length;
  document.querySelector('#continueLearning').innerHTML=data.courses.length?data.courses.slice(0,4).map(entry=>`<div class="account-row"><div><strong>${esc(entry.course.title)}</strong><small>${courseProgress(entry.courseId)}% complete · ${esc(entry.course.level||'All levels')}</small></div><b><a href="learn.html?id=${encodeURIComponent(entry.courseId)}">Continue →</a></b></div>`).join(''):empty('You have not enrolled in a course yet.');
  document.querySelector('#recentAccountOrders').innerHTML=data.orders.length?data.orders.slice(0,4).map(order=>`<div class="account-row"><div><strong>${esc(order.number)}</strong><small>${date(order.createdAt)} · ${esc(order.status)}</small></div><b>${money(order.total)}</b></div>`).join(''):empty('Your order activity will appear here.');
  document.querySelector('#accountCourses').innerHTML=data.courses.length?data.courses.map(renderCourseCard).join(''):empty('Explore JZ Academy and open a course to enroll.');
  document.querySelector('#certificateList').innerHTML=completed.length?completed.map(entry=>`<article class="certificate-card"><div><strong>${esc(entry.course.title)}</strong><p>Completed by ${esc(customer.name)}</p></div><button data-certificate="${esc(entry.courseId)}">View certificate</button></article>`).join(''):empty('Complete a course to unlock your first certificate.');
  document.querySelector('#accountOrders').innerHTML=data.orders.length?data.orders.map(renderOrder).join(''):empty('You have not placed an order yet.');
  document.querySelector('#savedProducts').innerHTML=data.savedProducts.length?data.savedProducts.map(product=>`<article class="saved-card"><div class="saved-card-visual" ${product.image?`style="background-image:url('${esc(product.image)}')"`:''}></div><div class="saved-card-copy"><h3>${esc(product.name)}</h3><p>${money(product.salePrice||product.price)} · ${esc(product.condition)}</p><a href="shop.html"><span>View in market</span><b>→</b></a></div></article>`).join(''):empty('No saved products yet.');
  document.querySelector('#savedCourses').innerHTML=data.savedCourses.length?data.savedCourses.map(course=>`<article class="saved-card"><div class="saved-card-visual"><strong>${esc(course.game||'JZ Academy')}</strong></div><div class="saved-card-copy"><h3>${esc(course.title)}</h3><p>${esc(course.level||'All levels')} · ${esc(course.duration||'Focused')}</p><a href="learn.html?id=${encodeURIComponent(course.id)}"><span>Open course</span><b>→</b></a></div></article>`).join(''):empty('No saved courses yet.');
  renderReviews();renderSupport();renderProfile();renderNotifications();
}
function reviewTargets(){const products=new Map();data.orders.forEach(order=>order.items.forEach(item=>products.set(item.id,item.name)));return{product:[...products].map(([id,name])=>({id,name})),course:data.courses.map(entry=>({id:entry.courseId,name:entry.course.title}))}}
function renderReviewTargets(){const type=document.querySelector('#reviewType').value,targets=reviewTargets()[type];document.querySelector('#reviewTarget').innerHTML=targets.length?targets.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join(''):'<option value="">No eligible items yet</option>'}
function renderReviews(){document.querySelector('#accountReviews').innerHTML=data.reviews.length?data.reviews.map(review=>`<div class="account-row"><div><strong>${'★'.repeat(review.rating)} ${esc(review.title||'Your review')}</strong><small>${esc(review.targetType)} · ${date(review.createdAt)}</small></div><b>${esc(review.status)}</b></div>`).join(''):empty('You have not submitted a review yet.');renderReviewTargets()}
function renderSupport(){document.querySelector('#supportHistory').innerHTML=data.support.length?data.support.map(ticket=>`<div class="account-row"><div><strong>${esc(ticket.subject)}</strong><small>${date(ticket.createdAt)} · ${(ticket.replies||[]).length} replies</small>${(ticket.replies||[]).slice(-1).map(reply=>`<p>${esc(reply.message)}</p>`).join('')}</div><b>${esc(ticket.status)}</b></div>`).join(''):empty('No support conversations yet.')}
function renderProfile(){const form=document.querySelector('#profileForm'),customer=data.customer,address=customer.addresses?.[0]||{},avatar=document.querySelector('#profileAvatar');form.elements.name.value=customer.name;form.elements.email.value=customer.email;form.elements.phone.value=customer.phone||'';form.elements.addressLabel.value=address.label||'';form.elements.address.value=address.address||'';form.elements.academy.checked=customer.preferences?.academy!==false;form.elements.orders.checked=customer.preferences?.orders!==false;form.elements.marketing.checked=customer.preferences?.marketing===true;avatar.textContent=customer.avatar?'':customer.name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();avatar.style.backgroundImage=customer.avatar?`url('${customer.avatar}')`:''}
function renderNotifications(){const unread=data.notifications.filter(item=>!(item.readBy||[]).includes(data.customer.id));document.querySelector('#notificationCount').textContent=unread.length;document.querySelector('#notificationList').innerHTML=data.notifications.length?data.notifications.map(item=>`<article class="notification-item ${(item.readBy||[]).includes(data.customer.id)?'':'unread'}" data-notification="${esc(item.id)}"><strong>${esc(item.title)}</strong><p>${esc(item.message)}</p><small>${date(item.createdAt)} · ${esc(item.type)}</small></article>`).join(''):empty('No notifications yet.')}
async function syncLocalSaved(){
  const localProducts=JSON.parse(localStorage.getItem('jz-market-saved')||'[]'),localCourses=JSON.parse(localStorage.getItem('jz-academy-saved')||'[]'),products=[...new Set([...(data.customer.savedProducts||[]),...localProducts])],courses=[...new Set([...(data.customer.savedCourses||[]),...localCourses])];
  if(products.length!==(data.customer.savedProducts||[]).length||courses.length!==(data.customer.savedCourses||[]).length)await api('/api/account/saved',{method:'PUT',body:JSON.stringify({products,courses})});
}
async function load(){data=await api('/api/account/me');await syncLocalSaved();data=await api('/api/account/me');render();setView(location.hash.slice(1)&&document.querySelector(`#${location.hash.slice(1)}View`)?location.hash.slice(1):'overview')}
function closePanels(){document.querySelector('.account-sidebar').classList.remove('open');document.querySelector('#notificationDrawer').classList.remove('open');document.querySelector('#accountOverlay').classList.remove('open')}
document.querySelectorAll('[data-account-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.accountView)));document.addEventListener('click',event=>{const button=event.target.closest('[data-go-account]');if(button)setView(button.dataset.goAccount)});
document.querySelector('#accountMobileMenu').addEventListener('click',()=>{document.querySelector('.account-sidebar').classList.add('open');document.querySelector('#accountOverlay').classList.add('open')});document.querySelector('#notificationButton').addEventListener('click',()=>{document.querySelector('#notificationDrawer').classList.add('open');document.querySelector('#accountOverlay').classList.add('open')});document.querySelector('#notificationClose').addEventListener('click',closePanels);document.querySelector('#accountOverlay').addEventListener('click',closePanels);
document.querySelector('#accountLogout').addEventListener('click',async()=>{await api('/api/account/logout',{method:'POST'}).catch(()=>{});localStorage.removeItem('jz-account-token');location.href='auth.html'});
document.querySelector('#reviewType').addEventListener('change',renderReviewTargets);
document.querySelector('#reviewForm').addEventListener('submit',async event=>{event.preventDefault();const payload=Object.fromEntries(new FormData(event.currentTarget));try{const result=await api('/api/account/reviews',{method:'POST',body:JSON.stringify(payload)});document.querySelector('#reviewMessage').textContent=result.message;event.currentTarget.reset();data=await api('/api/account/me');renderReviews()}catch(error){document.querySelector('#reviewMessage').textContent=error.message}});
document.querySelector('#supportForm').addEventListener('submit',async event=>{event.preventDefault();try{await api('/api/account/support',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});event.currentTarget.reset();document.querySelector('#supportMessage').textContent='Message sent. Support will reply here.';data=await api('/api/account/me');renderSupport()}catch(error){document.querySelector('#supportMessage').textContent=error.message}});
document.querySelector('#profileForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,payload={name:form.elements.name.value,phone:form.elements.phone.value,addresses:form.elements.address.value?[{id:data.customer.addresses?.[0]?.id,label:form.elements.addressLabel.value,address:form.elements.address.value}]:[],preferences:{academy:form.elements.academy.checked,orders:form.elements.orders.checked,marketing:form.elements.marketing.checked},currentPassword:form.elements.currentPassword.value,newPassword:form.elements.newPassword.value};try{await api('/api/account/profile',{method:'PATCH',body:JSON.stringify(payload)});form.elements.currentPassword.value='';form.elements.newPassword.value='';document.querySelector('#profileMessage').textContent='Account updated successfully.';data=await api('/api/account/me');render()}catch(error){document.querySelector('#profileMessage').textContent=error.message}});
document.querySelector('#profileAvatarFile').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});await api('/api/account/avatar',{method:'POST',body:JSON.stringify({data:dataUrl})});data=await api('/api/account/me');renderProfile();toast('Profile photo updated')}catch(error){document.querySelector('#profileMessage').textContent=error.message}finally{event.target.value=''}});
document.querySelector('#notificationList').addEventListener('click',async event=>{const item=event.target.closest('[data-notification]');if(!item)return;await api(`/api/account/notifications/${item.dataset.notification}`,{method:'PATCH'});data=await api('/api/account/me');renderNotifications()});
document.querySelector('#certificateList').addEventListener('click',event=>{const button=event.target.closest('[data-certificate]');if(!button)return;const entry=data.courses.find(item=>item.courseId===button.dataset.certificate),win=window.open('','_blank');win.document.write(`<title>JZ Academy Certificate</title><style>body{margin:0;padding:7vw;font-family:Arial;background:#f2f0e8;color:#111}main{min-height:70vh;padding:7vw;border:12px solid #151a14;text-align:center}small{letter-spacing:.2em}h1{font-size:8vw;margin:.3em 0}h2{font-size:3vw;color:#5e842c}p{margin-top:5vw}</style><main><small>JZ ACADEMY / CERTIFICATE OF COMPLETION</small><h1>${esc(data.customer.name)}</h1><span>has successfully completed</span><h2>${esc(entry.course.title)}</h2><p>Completed through practical learning · ${new Date().toLocaleDateString()}</p></main><script>print()<\/script>`);win.document.close()});
load().catch(error=>{document.body.innerHTML=`<main class="empty-account">${esc(error.message)}</main>`});
