const tokenKey='jz-account-token';
const resetToken=new URLSearchParams(location.search).get('reset');
if(localStorage.getItem(tokenKey)&&!resetToken)location.href='account.html';
const panels=[...document.querySelectorAll('[data-auth-panel]')],tabs=[...document.querySelectorAll('[data-auth-tab]')];
function showPanel(name){panels.forEach(panel=>panel.classList.toggle('active',panel.dataset.authPanel===name));tabs.forEach(tab=>tab.classList.toggle('active',tab.dataset.authTab===name))}
tabs.forEach(tab=>tab.addEventListener('click',()=>showPanel(tab.dataset.authTab)));document.querySelector('#showRecovery').addEventListener('click',()=>showPanel('recovery'));
async function submit(form,url,messageId){const message=document.querySelector(messageId),button=form.querySelector('[type=submit]');message.textContent='';button.disabled=true;try{const data=Object.fromEntries(new FormData(form));const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),result=await response.json();if(!response.ok)throw new Error(result.error);if(result.token){localStorage.setItem(tokenKey,result.token);location.href=new URLSearchParams(location.search).get('next')||'account.html'}else message.textContent=result.message}catch(error){message.textContent=error.message}finally{button.disabled=false}}
document.querySelector('#loginForm').addEventListener('submit',event=>{event.preventDefault();submit(event.currentTarget,'/api/account/login','#loginMessage')});
document.querySelector('#registerForm').addEventListener('submit',event=>{event.preventDefault();submit(event.currentTarget,'/api/account/register','#registerMessage')});
document.querySelector('#recoveryForm').addEventListener('submit',event=>{event.preventDefault();submit(event.currentTarget,'/api/account/recover','#recoveryMessage')});
document.querySelector('#resetForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,message=document.querySelector('#resetMessage'),password=form.elements.password.value;if(password!==form.elements.confirmPassword.value){message.textContent='Passwords do not match.';return}const button=form.querySelector('[type=submit]');button.disabled=true;try{const response=await fetch('/api/account/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:resetToken,password})}),result=await response.json();if(!response.ok)throw new Error(result.error);message.textContent=result.message;setTimeout(()=>{history.replaceState(null,'','auth.html');showPanel('login')},1200)}catch(error){message.textContent=error.message}finally{button.disabled=false}});
if(resetToken)showPanel('reset');
