const token=sessionStorage.getItem('jz-admin-token');if(!token)location.href='admin.html';
const esc=value=>{const element=document.createElement('span');element.textContent=String(value??'');return element.innerHTML};
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(value)||0);
async function api(url,options={}){const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}}),result=await response.json().catch(()=>({}));if(response.status===401)location.href='admin.html';if(!response.ok)throw new Error(result.error||'Request failed');return result}
let report,customers,orders,settings,discounts,audit,reviews,support,streams;
async function load(){[report,customers,orders,settings,discounts,audit,reviews,support,streams]=await Promise.all([api('/api/admin/reports'),api('/api/admin/customers'),api('/api/admin/orders'),api('/api/admin/settings'),api('/api/admin/discounts'),api('/api/admin/audit'),api('/api/admin/reviews'),api('/api/admin/support'),api('/api/admin/streams')]);render()}
function render(){
  document.querySelector('#metrics').innerHTML=[['Revenue',money(report.revenue)],['Open orders',report.open],['Accounts',customers.length],['Average order',money(report.average)],['Paid',money(report.paid)]].map(item=>`<div class="metric"><b>${item[1]}</b><small>${item[0]}</small></div>`).join('');
  document.querySelector('#lowStockList').innerHTML=report.lowStock.length?report.lowStock.map(product=>`<div class="list-row"><strong>${esc(product.name)}</strong><span>${esc(product.category)}</span><span>${product.stock} left</span><span>${money(product.price)}</span><a href="admin.html">Update</a></div>`).join(''):'<p>No low-stock products.</p>';
  const max=Math.max(1,...Object.values(report.byCategory));document.querySelector('#categoryReport').innerHTML=Object.entries(report.byCategory).map(([name,value])=>`<div class="bar-row"><span>${esc(name)}</span><div class="bar"><i style="width:${value/max*100}%"></i></div><b>${money(value)}</b></div>`).join('')||'<p>No sales data yet.</p>';
  document.querySelector('#customerList').innerHTML=customers.map(customer=>`<div class="list-row customer-admin-row"><div><strong>${esc(customer.name)}</strong><br><small>${esc(customer.email)} · ${customer.verified?'Verified':'Unverified'}</small></div><span>${customer.orders} orders · ${money(customer.spent)}</span><select data-enroll-customer="${customer.id}"><option value="">Enroll in course…</option>${streams.map(course=>`<option value="${course.id}">${esc(course.title)}</option>`).join('')}</select><button data-verify-customer="${customer.id}" data-value="${!customer.verified}">${customer.verified?'Unverify':'Verify'}</button><button data-reset-customer="${customer.id}">Reset password</button><button data-active-customer="${customer.id}" data-value="${!customer.active}">${customer.active?'Suspend':'Restore'}</button></div>`).join('')||'<p>No registered customers yet.</p>';
  document.querySelector('#notificationCustomer').innerHTML='<option value="">Choose customer</option>'+customers.map(customer=>`<option value="${customer.id}">${esc(customer.name)} · ${esc(customer.email)}</option>`).join('');
  document.querySelector('#paymentList').innerHTML=orders.map(order=>`<div class="list-row payment-admin-row"><div><strong>${esc(order.number)}</strong><br><small>${esc(order.customer.name)}</small></div><span>${money(order.total)}</span><select data-payment="${order.id}">${['pending','paid','refunded'].map(status=>`<option ${status===order.paymentStatus?'selected':''}>${status}</option>`).join('')}</select><select data-order-status="${order.id}">${['new','confirmed','processing','ready','completed','cancelled'].map(status=>`<option ${status===order.status?'selected':''}>${status}</option>`).join('')}</select><input data-tracking="${order.id}" value="${esc(order.trackingNumber||'')}" placeholder="Tracking number"><a href="invoice.html?id=${order.id}" target="_blank">Invoice</a></div>`).join('')||'<p>No payments yet.</p>';
  document.querySelector('#reviewAdminList').innerHTML=reviews.map(review=>`<div class="list-row"><div><strong>${'★'.repeat(review.rating)} ${esc(review.title||'Review')}</strong><br><small>${esc(review.customerName)} · ${esc(review.targetType)} · ${esc(review.targetId)}</small></div><span>${esc(review.comment)}</span><select data-review-status="${review.id}">${['pending','approved','rejected'].map(status=>`<option ${status===review.status?'selected':''}>${status}</option>`).join('')}</select><span></span><span></span></div>`).join('')||'<p>No submitted reviews.</p>';
  document.querySelector('#supportAdminList').innerHTML=support.map(ticket=>`<div class="support-admin-card" data-ticket="${ticket.id}"><header><div><strong>${esc(ticket.subject)}</strong><small>${esc(ticket.customerEmail)} · ${new Date(ticket.createdAt).toLocaleString()}</small></div><select data-support-status="${ticket.id}">${['open','in-progress','resolved'].map(status=>`<option ${status===ticket.status?'selected':''}>${status}</option>`).join('')}</select></header><p>${esc(ticket.message)}</p>${(ticket.replies||[]).map(reply=>`<blockquote>${esc(reply.message)} <small>${esc(reply.user)} · ${new Date(reply.at).toLocaleString()}</small></blockquote>`).join('')}<form data-support-reply="${ticket.id}"><input name="reply" placeholder="Write a reply…" required><button>Reply</button></form></div>`).join('')||'<p>No support tickets.</p>';
  document.querySelector('#discountList').innerHTML=discounts.map(discount=>`<div class="list-row"><strong>${esc(discount.code)}</strong><span>${discount.type}</span><span>${discount.value}${discount.type==='percent'?'%':''}</span><small>${discount.expiresAt||'No expiry'}</small><button data-delete-discount="${discount.id}">Delete</button></div>`).join('')||'<p>No discount codes.</p>';
  const form=document.querySelector('#settingsForm');for(const key of ['currency','lowStockThreshold','taxRate','contactEmail','contactPhone','bankInstructions'])form.elements[key].value=settings[key]??'';form.elements.deliveryZones.value=settings.deliveryZones.map(zone=>`${zone.id} | ${zone.name} | ${zone.fee}`).join('\n');
  document.querySelector('#auditList').innerHTML=audit.map(item=>`<div class="list-row"><strong>${esc(item.action)}</strong><span>${esc(item.user)}</span><span>${esc(item.detail)}</span><small>${new Date(item.at).toLocaleString()}</small><span></span></div>`).join('')||'<p>No activity recorded yet.</p>';
}
document.querySelectorAll('.ops-tabs button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.ops-tabs button').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.ops-panel').forEach(panel=>panel.classList.toggle('active',panel.id===button.dataset.panel))}));
document.querySelector('#customerList').addEventListener('change',async event=>{if(event.target.dataset.enrollCustomer&&event.target.value){await api(`/api/admin/customers/${event.target.dataset.enrollCustomer}`,{method:'PATCH',body:JSON.stringify({courseId:event.target.value})});await load()}});
document.querySelector('#customerList').addEventListener('click',async event=>{const reset=event.target.closest('[data-reset-customer]'),active=event.target.closest('[data-active-customer]'),verify=event.target.closest('[data-verify-customer]');try{if(reset){const password=prompt('Enter a temporary password with at least 8 characters:');if(password)await api(`/api/admin/customers/${reset.dataset.resetCustomer}`,{method:'PATCH',body:JSON.stringify({password})})}if(active)await api(`/api/admin/customers/${active.dataset.activeCustomer}`,{method:'PATCH',body:JSON.stringify({active:active.dataset.value==='true'})});if(verify)await api(`/api/admin/customers/${verify.dataset.verifyCustomer}`,{method:'PATCH',body:JSON.stringify({verified:verify.dataset.value==='true'})});await load()}catch(error){alert(error.message)}});
document.querySelector('#paymentList').addEventListener('change',async event=>{if(event.target.dataset.payment)await api(`/api/admin/orders/${event.target.dataset.payment}`,{method:'PATCH',body:JSON.stringify({paymentStatus:event.target.value})});if(event.target.dataset.orderStatus)await api(`/api/admin/orders/${event.target.dataset.orderStatus}`,{method:'PATCH',body:JSON.stringify({status:event.target.value})});if(event.target.dataset.tracking)await api(`/api/admin/orders/${event.target.dataset.tracking}`,{method:'PATCH',body:JSON.stringify({trackingNumber:event.target.value})});await load()});
document.querySelector('#reviewAdminList').addEventListener('change',async event=>{if(event.target.dataset.reviewStatus){await api(`/api/admin/reviews/${event.target.dataset.reviewStatus}`,{method:'PATCH',body:JSON.stringify({status:event.target.value})});await load()}});
document.querySelector('#supportAdminList').addEventListener('change',async event=>{if(event.target.dataset.supportStatus){await api(`/api/admin/support/${event.target.dataset.supportStatus}`,{method:'PATCH',body:JSON.stringify({status:event.target.value})});await load()}});
document.querySelector('#supportAdminList').addEventListener('submit',async event=>{const form=event.target.closest('[data-support-reply]');if(!form)return;event.preventDefault();await api(`/api/admin/support/${form.dataset.supportReply}`,{method:'PATCH',body:JSON.stringify({reply:new FormData(form).get('reply')})});await load()});
document.querySelector('#notificationForm').addEventListener('submit',async event=>{event.preventDefault();const payload=Object.fromEntries(new FormData(event.currentTarget));try{await api('/api/admin/notifications',{method:'POST',body:JSON.stringify(payload)});event.currentTarget.reset();document.querySelector('#notificationMessage').textContent='Notification sent.'}catch(error){document.querySelector('#notificationMessage').textContent=error.message}});
document.querySelector('#discountForm').addEventListener('submit',async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));await api('/api/admin/discounts',{method:'POST',body:JSON.stringify(values)});event.target.reset();await load()});
document.querySelector('#discountList').addEventListener('click',async event=>{if(event.target.dataset.deleteDiscount){await api(`/api/admin/discounts/${event.target.dataset.deleteDiscount}`,{method:'DELETE'});await load()}});
document.querySelector('#settingsForm').addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(event.target),zones=data.get('deliveryZones').split('\n').map(line=>{const[id,name,fee]=line.split('|').map(value=>value.trim());return{id,name,fee:Number(fee)}}).filter(zone=>zone.id&&zone.name);await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({...Object.fromEntries(data),deliveryZones:zones})});document.querySelector('#settingsMessage').textContent='Settings saved.';await load()});
document.querySelector('#downloadBackup').addEventListener('click',async()=>{const data=await api('/api/admin/backup'),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`jz-complete-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href)});
document.querySelector('#createSnapshot').addEventListener('click',async()=>{try{const result=await api('/api/admin/snapshot',{method:'POST'});document.querySelector('#backupMessage').textContent=`Full snapshot created: ${result.location}`;await load()}catch(error){document.querySelector('#backupMessage').textContent=error.message}});
document.querySelector('#restoreFile').addEventListener('change',async event=>{if(!event.target.files[0]||!confirm('Replace current business and account data with this backup?'))return;try{const data=JSON.parse(await event.target.files[0].text());await api('/api/admin/restore',{method:'POST',body:JSON.stringify(data)});document.querySelector('#backupMessage').textContent='Backup restored successfully.';await load()}catch(error){document.querySelector('#backupMessage').textContent=error.message}});
load().catch(error=>alert(error.message));
